import type { Metadata } from "next";
import { Space_Grotesk as Sans } from "next/font/google";
import "./index.css";
import { Navbar } from "@/components/ui/navbar";
import Footer from "@/components/Footer";
import { siteConfig } from "@/lib/config";

const geistSans = Sans({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: siteConfig.company.name,
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} bg-black text-white antialiased`}
            >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
